--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PocketEssential/UltraFaction
branches:
- master
projects:
  UltraFaction:
    path: "https://vignette.wikia.nocookie.net/cardwars/images/c/c1/CW_Icon_01.png/revision/latest?cb=20151106122306"
...
