#
# _    _ _ _             ______         _   _                 
#| |  | | | |           |  ____|       | | (_)                
#| |  | | | |_ _ __ __ _| |__ __ _  ___| |_ _  ___  _ __  ___ 
#| |  | | | __| '__/ _` |  __/ _` |/ __| __| |/ _ \| '_ \/ __|
#| |__| | | |_| | | (_| | | | (_| | (__| |_| | (_) | | | \__ \
# \____/|_|\__|_|  \__,_|_|  \__,_|\___|\__|_|\___/|_| |_|___/
#
# Made by PocketEssential Copyright 2016 ©
#
# This is a public software, you cannot redistribute it a and/or modify any way
# unless otherwise given permission to do so.
#
# Author: The PocketEssential Team
# Link: https://github.com/PocketEssential
#
#|------------------------------------------------ UltraFaction ------------------------------------------------|
#| - If you made a mistake in the config, either edit it, or delete the config file, then restart your server!  |
#| - If the issue persists, report it at https://github.com/PocketEssential/UltraFaction/issues                 |
#|--------------------------------------------------------------------------------------------------------------|


# Available: english (You can also create your own!)
Language: english

# Set default data type provider for UltraFaction
# - mysql, sqlite, yaml

data-provider: sqlite

#Supported, EconomyAPI, MassiveEconomy (Todo)
Economy: EconomyAPI

# If your using MySQL : Enter the details before!
MySql:
    Host: localhost
    Username: root
    Password: 12345678
    Database: UltraFaction

# Max members a faction can have: They can bypass it with the  correct permission
Max_Member: 10

# Choose if you want to allow players to claim plots at spawn
Spawn_Claim: false

# Claim plot size - In blocks / Limit of plots a faction can have | 0 means none.
Claim_Size: 20
Claim_Limit: 0

# Allow mobs to destroy a claim plot?
Mob_Grief: false

# Allow none-faction members to spawn eggs in a claimed plot?
Player_Grief: false

# Max power a faction can have. 0.0 means there is not. Set it to a positive value in case you want to use this feature!
factionPowerMax: 0.0

# Limit the length of faction names here.
factionNameLengthMin: 3
factionNameLengthMax: 16

# If you set this to false players can't set homes or teleport home.
Home_Enable: true

# Can faction members attack each other?
Can_Attack: false

# Price a faction must pay to be able to claim a plot! 0 - means free
Claim_Price: 0

# Choose if you wanna enable or disable the map feature!
Map_System: true
