#
# 
# 8888888b.                   888               888    8888888888                                    888    d8b          888 
# 888   Y88b                  888               888    888                                           888    Y8P          888 
# 888    888                  888               888    888                                           888                 888 
# 888   d88P .d88b.   .d8888b 888  888  .d88b.  888888 8888888   .d8888b  .d8888b   .d88b.  88888b.  888888 888  8888b.  888 
# 8888888P" d88""88b d88P"    888 .88P d8P  Y8b 888    888       88K      88K      d8P  Y8b 888 "88b 888    888     "88b 888 
# 888       888  888 888      888888K  88888888 888    888       "Y8888b. "Y8888b. 88888888 888  888 888    888 .d888888 888 
# 888       Y88..88P Y88b.    888 "88b Y8b.     Y88b.  888            X88      X88 Y8b.     888  888 Y88b.  888 888  888 888 
# 888        "Y88P"   "Y8888P 888  888  "Y8888   "Y888 8888888888 88888P'  88888P'  "Y8888  888  888  "Y888 888 "Y888888 888 
#
# Copyright (C) 2016 PocketEssential
#
# This is a public software, you cannot redistribute it a and/or modify any way
# unless otherwise given permission to do so.
#
# @author PocketEssential
# @link https://github.com/PocketEssential/
#
#---- UltraFaction
# - If you made a mistake. Just delete the config! and restart server.
# - If the issue persists, Open an issue and we"ll help out :)
#----
#

# Available: english (You can also create your own!)
Language: english


# Max members a faction can have: They can bypass it with the  correct permission
Max_Member: 10

# Choose if you want to allow players to claim plots at spawn
Spawn_Claim: false

# Claim plot size - In blocks / Limit of plots a faction can have | 0 means none.
Claim_Size: 20
Claim_Limit: 0

# Allow mobs to destroy a claim plot?
Mob_Grief: false

# Allow none-faction members to spawn eggs in a claimed plot?
Player_Grief: false

# Max power a faction can have. 0.0 means there is not. Set it to a positive value in case you want to use this feature!
factionPowerMax: 0.0

# Limit the length of faction names here.
factionNameLengthMin: 3
factionNameLengthMax: 16

# If you set this to false players can't set homes or teleport home.
Home_Enable: true

# Can faction members attack each other?
Can_Attack: false

# Price a faction must pay to be able to claim a plot! 0 - means free
Claim_Price: 0

# Choose if you wanna enable or disable the map feature!
Enable: true
